import sys
from pathlib import Path
from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles

# Add kineforge to path dynamically relative to file location
sys.path.append(str(Path(__file__).resolve().parents[2] / 'kineforge'))
# Add project root to sys.path to allow absolute imports of backend package
sys.path.append(str(Path(__file__).resolve().parents[1]))


from backend.api import health, dynamics, packages

app = FastAPI(
    title="Robodimm PRO Python Backend",
    description="Local dynamics calculation engine using Pinocchio and Kineforge libraries",
    version="1.0.0"
)

# Restricted CORS configuration
ALLOWED_ORIGINS = [
    "https://customrobotics.es",
    "https://www.customrobotics.es",
    "http://localhost:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:5174"
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=ALLOWED_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Custom middleware to handle Private Network Access preflight requests.
# Added AFTER CORSMiddleware in code, so it executes OUTERMOST in the ASGI chain,
# ensuring OPTIONS responses generated by CORSMiddleware receive the PNA header.
@app.middleware("http")
async def private_network_preflight_middleware(request: Request, call_next):
    response = await call_next(request)
    if request.method == "OPTIONS":
        response.headers["Access-Control-Allow-Private-Network"] = "true"
    return response

# Mount static files to serve package meshes
PACKAGES_DIR = Path.home() / ".robodimm" / "packages"
PACKAGES_DIR.mkdir(parents=True, exist_ok=True)
app.mount("/api/packages/static", StaticFiles(directory=str(PACKAGES_DIR)), name="packages_static")

# Include routers
app.include_router(health.router, prefix="/api")
app.include_router(dynamics.router, prefix="/api")
app.include_router(packages.router, prefix="/api")

if __name__ == "__main__":
    import uvicorn
    import os
    # Bind strictly to local loopback (127.0.0.1) by default, or override via environment variable for Docker namespaces
    host = os.environ.get("ROBODIMM_HOST", "127.0.0.1")
    uvicorn.run("backend.main:app", host=host, port=8001, reload=False)
